const EMPLOYEE_FIELD_LABELS: Record<string, string> = {
  last_name: 'Фамилия',
  first_name: 'Имя',
  middle_name: 'Отчество',
  email: 'E-mail',
  phone: 'Телефон',
  password: 'Пароль',
  telegram: 'Telegram',
  city: 'Город',
  inn: 'ИНН',
  hikvision_id: 'Hikvision ID',
  gender: 'Пол',
  birth_date: 'Дата рождения',
  marital_status: 'Семейное положение',
  registered_address: 'Адрес регистрации',
  actual_address: 'Место проживания',
  department_id: 'Отдел',
  position_id: 'Должность',
  branch_id: 'Филиал',
  manager_id: 'Руководитель',
  business_role_id: 'Роль',
  position_change_reason_text: 'Причина смены должности',
  position_change_basis_filename: 'Файл-основание',
  position_change_basis_file_base64: 'Файл-основание',
  termination_date: 'Дата увольнения',
  termination_reason: 'Причина увольнения',
  name: 'Имя',
  relative: 'Родство',
  institution: 'Учебное заведение',
  degree: 'Степень',
  specialization: 'Специализация',
  started_at: 'Дата начала',
  ended_at: 'Дата окончания',
  amount: 'Сумма',
  currency: 'Валюта',
  prepaid_percent: 'Аванс',
  days_per_week: 'Дней в неделю',
  hours_per_day: 'Часов в день',
  company: 'Компания',
  position: 'Должность',
  description: 'Описание',
  type: 'Тип',
  details: 'Детали',
  title: 'Название',
  filename: 'Файл',
  file_base64: 'Файл',
  document_type_id: 'Тип документа',
}

export const getEmployeeFieldLabel = (field: string): string =>
  EMPLOYEE_FIELD_LABELS[field] ?? field

export { EMPLOYEE_FIELD_LABELS }
